language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script: vendor/bin/phpunit --verbose --coverage-text

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
  email: false